# comment - https://dba.stackexchange.com/questions/57075/line-comment-in-mongodb-config-file
# this file is required after macOS upgrade which blocked access to default dbPath

systemLog:
  destination: file
  path: /usr/local/var/log/mongodb/mongo.log
  logAppend: true
storage:
  dbPath: /Users/c/data/db
net:
  bindIp: 127.0.0.1
